-- Add room_status column to rooms.
-- A single-sentence statement of the most important blocker or current state of play.
-- Generated by generate-room-summary alongside room_summary in a single model call.
-- Nullable -- null until the first generation runs after the migration is applied.

alter table rooms
  add column room_status text,
  add column room_status_updated_at timestamptz;
